### ISSUE TITLE
include AzBI in modules and ensure that it works correctly with cli

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/cli#15]
The ability to call the module "Azure Basic Infrastructure" from the E wrapper should be added to enable interaction with this module.

**Comment by atsikham** [comment]
Tested with pre-built azbi:dev Docker image using commands from [PR](https://github.com/epiphany-platform/cli/pull/27) description. Checked that resource group with requested resources was created in Azure.
Created new #32 task.
