### ISSUE TITLE
Add GitHub templates

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/cli#30]
**Is your feature request related to a problem? Please describe.**
We need to add GitHub templates to this repository. 

**Describe the solution you'd like**
Like in https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/57 

**Describe alternatives you've considered**
Nope. 

**Additional context**
Nope.

**Comment by rafzei** [comment]
Verify it in all epiphany-platform repositories.

**Comment by rpudlowski93** [comment]
@atsikham Should we move it to DoD? I checked and it is possible to create bug issue and feature request using template.
