### ISSUE TITLE
Export / Import environment

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/cli#31]
**Is your feature request related to a problem? Please describe.**
We don't have option to easy share configurations between machines or users. 

**Describe the solution you'd like**
It would be good to have `e env export ...` and `e env import ...` commands to be implemented. With those it would be very simple to share configurations between machines or users. 

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by atsikham** [comment]
It's necessary to verify at least:
* passing all unit tests
* `e export/import` commands and its help messages

**Comment by przemyslavic** [comment]
All tests pass (111 unit tests were run locally and in the pipeline).
Many different test cases related to import and export environments were checked.
Reported one minor issue: [#39](https://github.com/epiphany-platform/cli/issues/39).
